PACKAGE_NAME="xps7390-webcam"
PACKAGE_VERSION="0.1.0"
AUTOINSTALL="yes"

MAKE[0]="make KDIR=${kernel_source_dir} modules"
CLEAN="make KDIR=${kernel_source_dir} clean-modules"

BUILT_MODULE_NAME[0]="int346f"
BUILT_MODULE_LOCATION[0]="driver/int346f"
DEST_MODULE_LOCATION[0]="/updates/xps7390-webcam"

BUILT_MODULE_NAME[1]="ov01a10-i346f"
BUILT_MODULE_LOCATION[1]="driver/ov01a10"
DEST_MODULE_LOCATION[1]="/updates/xps7390-webcam"

BUILT_MODULE_NAME[2]="intel-ipu4p"
BUILT_MODULE_LOCATION[2]="driver/ipu4p"
DEST_MODULE_LOCATION[2]="/updates/xps7390-webcam"

BUILT_MODULE_NAME[3]="intel-ipu4p-isys"
BUILT_MODULE_LOCATION[3]="driver/ipu4p"
DEST_MODULE_LOCATION[3]="/updates/xps7390-webcam"
